version: '3.9'

services:
  postgres:
    container_name: my_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_postgres

volumes:
  postgres_data:

# networks:
#   - my_postgres